environment:
  type: 'app'
  name: '环卫特征检测'
  device: '环卫特征检测v1.1'
  description: ''
  version: '1.1.0'
  author: '字段【人特征，车特征，文件名】'
  email: ''
  widgets:
    environment_image:
      name: '图像'
      description: '显示图像'
      receiver: ''
      template: 'environment-image'
      fields:
        filename:
          name: '图像'
          type: 3
          symbol: ''
    environment_data:
      name: '特征数据'
      description: '特征数据'
      receiver: ''
      template: 'environment-data'
      fields:
        p_confidence:
          name: '人识别度'
          type: 3
          symbol: ''
        c_confidence:
          name: '车识别度'
          type: 3
          symbol: ''