mqtt:
  broker: 39.98.176.26:1883
  user: root
  pass: root
  topicToPublish: device/attributes
  topicToSubscribe: device/attributes
  topicToStatus: device/status

url: dev.thingspanel.cn

tcp:
  port: :9998

api:
  http_host: 127.0.0.1:8083

plugin:
  http_host: 127.0.0.1:503
