mqtt:
  broker: 127.0.0.1:1883
  clientid: ThingsPanel
  user: guest
  pass: guest
  topicToPublish: thingspanel.telemetry
  topicToSubscribe: thingspanel.operation

tcp:
  port: 9505

amqp:
  host: rabbitmq
  port: 5672
  user: guest
  pass: guest