probe:
  type: "app"
  name: "探针监测"
  device: "探针监测v1.0"
  description: ""
  version: '1.0.0'
  author: '字段【温度，湿度，噪声，电量，...】'
  email: ''
  widgets:
    gps_marker:
      name: "GPS位置标记"
      description: "GPS位置信息显示"
      receiver: ""
      thumbnail: "/gps.png"
      template: "gps-marker"
      fields:
        title:
          name: "名称"
          type: 3
          symbol: ""
        lng:
          name: "经度"
          type: 3
          symbol: ""
        lat:
          name: "纬度"
          type: 3
          symbol: ""
        address:
          name: "地址"
          type: 3
          symbol: ""
    formaldehyde_value:
      name: '当前温度'
      description: '当前温度'
      receiver: ''
      template: 'tz-temperature-current-value'
      fields:
        temp:
          name: '温度'
          type: 3
          symbol: '℃'
    TzHumidityCurrentValue:
      name: '当前湿度'
      description: '当前湿度'
      receiver: ''
      template: 'tz-humidity-current-value'
      fields:
        hum:
          name: '湿度'
          type: 3
          symbol: '%Rh'
    pm25_value:
      name: '当前电量'
      description: '当前电量'
      receiver: ''
      thumbnail: '/pm25.png'
      template: 'tz-electric-quantity-value'
      fields:
        battery:
          name: '电量'
          type: 3
          symbol: '%'
    pm25_line:
      name: '电量曲线'
      description: '电量曲线'
      receiver: 'Pm25'
      thumbnail: '/pm25.png'
      template: 'tz-electric-quantity-line'
      fields:
        battery:
          name: '电量'
          type: 3
          symbol: '%'
    humiture_line:
      name: '湿度曲线'
      description: '湿度曲线'
      receiver: ''
      template: 'tz-humidity-current-line'
      fields:
        hum:
          name: '湿度'
          type: 3
          symbol: '%Rh'
    humiture_chart:
      name: '温度曲线'
      description: '温度曲线'
      receiver: ''
      template: 'tz-temperature-current-line'
      fields:
        temp:
          name: '温度'
          type: 3
          symbol: '℃'
    noise_chart:
      name: '噪音当前值'
      description: '噪音当前值'
      receiver: ''
      template: 'noise-value'
      fields:
        noise:
          name: '噪音'
          type: 3
          symbol: 'dB'
    noise_line:
      name: '噪音曲线'
      description: '噪音曲线'
      receiver: ''
      template: 'noise-line'
      fields:
        noise:
          name: '噪音'
          type: 3
          symbol: 'dB'
    device_warning:
      name: '设备警告统计'
      description: '设备警告统计'
      receiver: ''
      template: 'device-warning'
      fields:
        warn:
          name: '设备警告'
          type: 3
          symbol: ''
    accelerated_X:
      name: 'X轴加速度'
      description: 'X轴加速度'
      receiver: ''
      template: 'tz-accelerated-x-value'
      fields:
        acceleratedx:
          name: 'X轴加速度'
          type: 3
          symbol: 'm²/s'
    accelerated_Y:
      name: 'Y轴加速度'
      description: 'Y轴加速度'
      receiver: ''
      template: 'tz-accelerated-y-value'
      fields:
        acceleratedy:
          name: 'Y轴加速度'
          type: 3
          symbol: 'm²/s'
    accelerated_Z:
      name: 'Z轴加速度'
      description: 'Z轴加速度'
      receiver: ''
      template: 'tz-accelerated-z-value'
      fields:
        acceleratedy:
          name: 'Z轴加速度'
          type: 3
          symbol: 'm²/s'