name: Deploy to Server

on:
  push:
    branches:
      - main  # 或者您想要部署的其他分支名

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy and Check contents
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: ${{ secrets.DC_HOST }}
        user: ${{ secrets.DC_USER }}
        pass: ${{ secrets.DC_PASS }}
        first_ssh: "ls -la /home/hd/"
        scp: |
          - source: .
            target: /home/hd/
        last_ssh: "ls -la /home/hd/"
