name: Deploy to Server

on:
  push:
    branches:
      - main  # 或者您想要部署的其他分支名

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy and Check contents
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: ${{ secrets.DEV_HOST }}
        user: ${{ secrets.DEV_USER }}
        pass: ${{ secrets.DEV_PASS }}
        first_ssh: |
          rm -rf /home/hd/*   # 清空目录，但保留目录本身
          ls -la /home/hd/    # 显示清空后的目录
        scp: |
          ./* => /home/hd/
        last_ssh: |
          go build 
          ls -la /home/hd/  # 显示传输后的目录
          ./z-shell.sh     # 执行脚本
