name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/thingspanel/thingspanel-go:latest
    - name: Login in
      run: echo $ACTION_TOKEN | docker login ghcr.io -u zjhong --password-stdin
    - name: Push
      run: docker push ghcr.io/thingspanel/thingspanel-go:latest

